HospitalWeb/HospitalWeb/Models/Especialidad.cs
using System;
using System.Collections.Generic;

namespace HospitalWeb.Models
{
    public partial class Especialidad
    {
        public Especialidad()
        {
            Doctor = new HashSet<Doctor>();
        }

        public int Iidespecialidad { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}

HospitalWeb/HospitalWeb/Controllers/EspecialidadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HospitalWeb.Clases;
using HospitalWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HospitalWeb.Controllers
{
    public class EspecialidadController : Controller
    {
        // GET: EspecialidadController
        public ActionResult Index(EspecialidadCLS oEspecialidadCLS)
        {
            List<EspecialidadCLS> listaEspecialidad = new List<EspecialidadCLS>();

            using (BDHospitalContext db = new BDHospitalContext())
            {

                if (oEspecialidadCLS.nombre == null || oEspecialidadCLS.nombre == "")
                {
                    listaEspecialidad = (from x in db.Especialidad
                                         where x.Bhabilitado == 1
                                         select new EspecialidadCLS
                                         {
                                             iidespeciadlidad = x.Iidespecialidad,
                                             nombre = x.Nombre,
                                             descripcion = x.Descripcion

                                         }).ToList();
                    ViewBag.Filtro = "";
                }
                else
                {
                    listaEspecialidad = (from x in db.Especialidad
                                         where x.Bhabilitado == 1 &&
                                         x.Nombre.Contains(oEspecialidadCLS.nombre)
                                         select new EspecialidadCLS
                                         {
                                             iidespeciadlidad = x.Iidespecialidad,
                                             nombre = x.Nombre,
                                             descripcion = x.Descripcion

                                         }).ToList();

                    ViewBag.Filtro = oEspecialidadCLS.nombre;
                }

                

            }

            return View(listaEspecialidad);
        }



        //// GET: EspecialidadController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: EspecialidadController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EspecialidadController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EspecialidadCLS oEspecialidadCLS)
        {
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    if (!ModelState.IsValid)
                    {
                        return View(oEspecialidadCLS);
                    }
                    else
                    {
                        Especialidad oEspecialidad = new Especialidad();
                        oEspecialidad.Bhabilitado = 1;
                        oEspecialidad.Nombre = oEspecialidadCLS.nombre;
                        oEspecialidad.Descripcion = oEspecialidadCLS.descripcion;
                        db.Especialidad.Add(oEspecialidad);
                        db.SaveChanges();
                    }

                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(oEspecialidadCLS);
            }
        }

        // GET: EspecialidadController/Edit/5
        public ActionResult Edit(int id)
        {

            EspecialidadCLS oEspecialidadCLS = new EspecialidadCLS();
            using (BDHospitalContext db = new BDHospitalContext())
            {
                oEspecialidadCLS = (from x in db.Especialidad
                                    where x.Iidespecialidad == id
                                    select new EspecialidadCLS
                                    {
                                        iidespeciadlidad = x.Iidespecialidad,
                                        nombre = x.Nombre,
                                        descripcion = x.Descripcion
                                    }).First();

            }

            return View(oEspecialidadCLS);
        }

        // POST: EspecialidadController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, EspecialidadCLS oEspecialidadCSL)
        {
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    if (!ModelState.IsValid)
                    { return View(oEspecialidadCSL); }
                    else
                    {
                        Especialidad objEspecial = new Especialidad();
                        objEspecial.Nombre = oEspecialidadCSL.nombre;
                        objEspecial.Descripcion = oEspecialidadCSL.descripcion;
                        objEspecial.Iidespecialidad = oEspecialidadCSL.iidespeciadlidad;
                        objEspecial.Bhabilitado = 1;
                        db.Especialidad.Update(objEspecial);
                        db.SaveChanges();
                    }

                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(oEspecialidadCSL);
            }
        }

        // GET: EspecialidadController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: EspecialidadController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id) //, IFormCollection collection)
        {
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    Especialidad oEspecialidad = db.Especialidad
                                                 .Where(x => x.Iidespecialidad == id).First();

                    //Eliminar fisica
                    //db.Remove(oEspecialidad);
                    //Eliminacion logica
                    oEspecialidad.Bhabilitado = 0;
                    db.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

HospitalWeb/HospitalWeb/Views/Especialidad/Create.cshtml
@model HospitalWeb.Clases.EspecialidadCLS

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>EspecialidadCLS</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="frmWeb">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="iidespeciadlidad" class="control-label"></label>
                <input asp-for="iidespeciadlidad" class="form-control" />
                <span asp-validation-for="iidespeciadlidad" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" onclick="Guardar()"   value ="Create" class="btn btn-primary" />
              
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<script>

    function Guardar() {

        //document.getElementById("idEspecialidad").value = id;
        //codigo de pop up

        //Validar()

        Swal.fire({
            title: "Desea agregar el registro?",
            text: "Desea agregar la informacion en la base de datos",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si!'
        }).then((result) => {
            if (result.value) {
                //enviar a base de datos
                var frmWeb = document.getElementById("frmWeb");
                frmWeb.submit();


                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: 'Cambios guardados exitosamente!',
                    showConfirmButton: false,
                    timer: 1500
                })

            }
        })


    }
</script>

HospitalWeb/HospitalWeb/Views/Especialidad/Edit.cshtml
@model HospitalWeb.Clases.EspecialidadCLS

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EspecialidadCLS</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="frmWeb">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="iidespeciadlidad" class="control-label"></label>
                <input asp-for="iidespeciadlidad" class="form-control" />
                <span asp-validation-for="iidespeciadlidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" onclick="Guardar()"  value="Guardar" class="btn btn-primary" />
                <a class="btn btn-danger" asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}



<script>

    function Guardar() {

        //document.getElementById("idEspecialidad").value = id;
        //codigo de pop up
        //alert("SI");

        //Validar()

        Swal.fire({
            title: "Desea modificar el registro?",
            text: "Desea modificar la informacion en la base de datos",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si!'
        }).then((result) => {
            if (result.value) {

                //enviar a base de datos
                var frmWeb = document.getElementById("frmWeb");
                frmWeb.submit();
            }
        })


    }
</script>

HospitalWeb/HospitalWeb/Views/Especialidad/Index.cshtml
@model IEnumerable<HospitalWeb.Clases.EspecialidadCLS>

@{
    ViewData["Title"] = "Index";
    var filtro = ViewBag.Filtro;
}

<h1>Especialidades</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Nuevo</a>
</p>


<form asp-controller="Especialidad" asp-action="Index" method="post" class="mb-2"
      style="display:grid;grid-template-columns:1fr 2fr 1fr">
    <label>Ingrese nombre Especialidad:</label>
    <input type="text" class="form form-control" name="nombre" value="@filtro" />
    @*<input type="submit" value="Enviar" class="btn btn-info" />*@

    <input type="button" value="Enviar" class="btn btn-info" />

</form>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.iidespeciadlidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                Operaciones
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.iidespeciadlidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@

                <a href="/Especialidad/Edit/@item.iidespeciadlidad" class="fa fa-refresh btn btn-primary"></a>
                 
                <i class="fa fa-trash-o btn btn-danger" onclick="Eliminar(@item.iidespeciadlidad)"></i>


            </td>
        </tr>
}
    </tbody>
</table>

<form id="frmEliminar" asp-action="Delete" asp-controller="Especialidad" method="post">
    <input type="hidden" name="id" id="idEspecialidad" />
</form>


<script>

    function Eliminar(id) {

        document.getElementById("idEspecialidad").value = id;
        //codigo de pop up
        //alert("SI");

        //Validar()

        Swal.fire({
            title: "Desea eliminar el registro?",
            text: "Desea eliminar la informacion en la base de datos",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si!'
        }).then((result) => {
            if (result.value) {
                alert("SI");
                //enviar a base de datos
                var frmEliminar = document.getElementById("frmEliminar");
                frmEliminar.submit();

                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: 'Cambios guardados exitosamente!',
                    showConfirmButton: false,
                    timer: 1500
                })

            }
        })


    }
</script>