CURSO01/CURSO01/Models/Sede.cs
using System;
using System.Collections.Generic;

namespace CURSO01.Models
{
    public partial class Sede
    {
        public Sede()
        {
            Cita = new HashSet<Cita>();
            Doctor = new HashSet<Doctor>();
        }

        public int Iidsede { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<Cita> Cita { get; set; }
        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}

CURSO01/CURSO01/Controllers/SedeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CURSO01.Clases;
using CURSO01.Models;
using Microsoft.AspNetCore.Mvc;

namespace CURSO01.Controllers
{
    public class SedeController : Controller
    {
        public IActionResult Index(SedeCLS oSedeCLS)
        {

            List<SedeCLS> listaSede = new List<SedeCLS>();
            using (BDHospitalContext db = new BDHospitalContext())
            {
                if (oSedeCLS.nombreSede == null || oSedeCLS.nombreSede == "")
                {

                    listaSede = (from sede in db.Sede
                                 where sede.Bhabilitado == 1
                                 select new SedeCLS
                                 {
                                     iidSede = sede.Iidsede,
                                     nombreSede = sede.Nombre,
                                     direccion = sede.Direccion
                                 }).ToList();

                    ViewBag.nombreSede = "";
                }
                else
                {

                    listaSede = (from sede in db.Sede
                                 where sede.Bhabilitado == 1
                                 && sede.Nombre.Contains(oSedeCLS.nombreSede)
                                 select new SedeCLS
                                 {
                                     iidSede = sede.Iidsede,
                                     nombreSede = sede.Nombre,
                                     direccion = sede.Direccion
                                 }).ToList();

                    ViewBag.nombreSede = oSedeCLS.nombreSede;
                }

            }

            return View(listaSede);
        }
    }
}

CURSO01/CURSO01/Views/Sede/Index.cshtml
@model IEnumerable<CURSO01.Clases.SedeCLS>

@{
    ViewData["Title"] = "Index";
    string nombreSede = ViewBag.nombreSede;

}

<h1>Index</h1>


<form id="frmEnviar" asp-controller="Sede" asp-action="index" method="post"
      class="mb-2">

    <label>Nombre Sede</label>
    <input type="text" name="nombreSede" class="form form-control" onkeyup="Buscar()" value="@nombreSede" />

</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.iidSede)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombreSede)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccion)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.iidSede)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombreSede)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.direccion)
                </td>
            </tr>
        }
    </tbody>
</table>



<script>
    function Limpiar() {
        
        document.getElementById("frmEnviar").submit();
    }
</script>