WebCRUD/WebCRUD/Models/TipoUsuario.cs
using System;
using System.Collections.Generic;

namespace WebCRUD.Models
{
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            TipoUsuarioPagina = new HashSet<TipoUsuarioPagina>();
            Usuario = new HashSet<Usuario>();
        }

        public int Iidtipousuario { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<TipoUsuarioPagina> TipoUsuarioPagina { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}

WebCRUD/WebCRUD/Controllers/TipoUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebCRUD.Models;

namespace WebCRUD.Controllers
{
    public class TipoUsuarioController : Controller
    {
        // GET: TipoUsuarioController1cs
        public ActionResult Index()
        {
            List<TipoUsuarioCLS> listaTipoUsuario = new List<TipoUsuarioCLS>();

            using (BDHospitalContext db = new BDHospitalContext())
            {
                
                listaTipoUsuario = (from x in db.TipoUsuario
                                    where x.Bhabilitado == 1
                                    select new TipoUsuarioCLS 
                                    {
                                        iidTipoUsuario = x.Iidtipousuario,
                                        nombre = x.Nombre,
                                        descripcion = x.Descripcion
                                    }).ToList();


            }

            return View(listaTipoUsuario);
        }

        //// GET: TipoUsuarioController1cs/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: TipoUsuarioController1cs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoUsuarioController1cs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TipoUsuarioCLS  oTipoUsuarioCLS)
        {
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    if (!ModelState.IsValid)
                    {
                        return View(oTipoUsuarioCLS);
                    }
                    else
                    {
                        TipoUsuario tipoUsuario = new TipoUsuario();
                        tipoUsuario.Bhabilitado = 1;
                        tipoUsuario.Nombre = oTipoUsuarioCLS.nombre;
                        tipoUsuario.Descripcion = oTipoUsuarioCLS.descripcion;
                        db.Add(tipoUsuario);
                        db.SaveChanges();

                    }

                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoUsuarioController1cs/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TipoUsuarioController1cs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //// GET: TipoUsuarioController1cs/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: TipoUsuarioController1cs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int Iidtipousuario)
        {

            using (BDHospitalContext db = new BDHospitalContext())
            {
                TipoUsuario oTipoUsuario = db.TipoUsuario
                    .Where(x => x.Iidtipousuario == Iidtipousuario).First();
                //db.TipoUsuario.Remove(oTipoUsuario);
                oTipoUsuario.Bhabilitado = 0;
                db.SaveChanges();
            }
            return RedirectToAction("Index");


            //return RedirectToAction("Index");
        }
    }
}

WebCRUD/WebCRUD/Views/TipoUsuario/Create.cshtml
@model WebCRUD.TipoUsuarioCLS

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TipoUsuarioCLS</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="frmEnviar" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="iidTipoUsuario" class="control-label"></label>
                <input asp-for="iidTipoUsuario" class="form-control" />
                <span asp-validation-for="iidTipoUsuario" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" value="Guardar" onclick="abrirModal()" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<script>
    function abrirModal() {
        Swal.fire({
            title: "Desea guardar los datos?",
            text: "Desea guadar la informacion en la base de datos",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si!'
        }).then((result) => {
            if (result.value) {
                //enviar a base de datos
                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

WebCRUD/WebCRUD/Views/TipoUsuario/Index.cshtml
@model IEnumerable<WebCRUD.TipoUsuarioCLS>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.iidTipoUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.iidTipoUsuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    <i class="fa fa-trash-o btn btn-danger"
                       onclick="Eliminar(@item.iidTipoUsuario)"></i>
                </td>
            </tr>
        }
    </tbody>
</table>

<form asp-action="Delete" asp-controller="TipoUsuario" method="post" id="frmEliminar">
    <input type="hidden" id="txtID" name="Iidtipousuario" />
</form>


<script>

    function Eliminar(idEspecialidad) {
        document.getElementById("txtID").value = idEspecialidad;

        Swal.fire({
            title: "Desea eliminar el registro?",
            text: "Desea eliminar la informacion en la base de datos",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si!'
        }).then((result) => {
            if (result.value) {
                //enviar a base de datos
                var frmEliminar = document.getElementById("frmEliminar");
                frmEliminar.submit();
            }
        })

    }

</script>